"""The calibration table: what the verifier scored on inputs of known quality.

Why this exists
---------------
The assignment requires it, in §4:

    Calibration-tested before submission. Run the verifier on at least: the
    untouched base model, the reference counterpart, your probe fine-tune, a
    deliberately broken checkpoint, and (if feasible) a deliberate reward-hacking
    attempt. Report the reward each produced and confirm the ordering matches
    expectation. A verifier that has only ever seen "good" inputs is untested.

All of those runs had happened. What was missing is the second sentence: the
results lived in three unrelated places -- a JSON crash matrix for the mol task, a
hand-written Markdown table for the two post-training tasks, and Harbor job
directories for the live runs -- and nowhere did anything state whether the
*ordering* came out as expected. "Report" means one artifact, not three sources a
reader has to merge.

This assembles that artifact from the committed records, so it cannot drift from
them, and applies the ordering test the assignment asks for.

    python common/calibration.py            # rewrite docs/calibration.md
    python common/calibration.py --check    # exit 1 if stale or an ordering fails

The ordering test
-----------------
Two properties, per task:

  1. Every deliberately broken or substituted input scores exactly 0.
  2. A submission that does not adapt the model scores STRICTLY BELOW the oracle.

The second is the one with teeth, and it is why this table is worth building: the
protein task fails it. Its frozen probe and its oracle both score 1.0, because both
of its fixed tiers sit below the frozen ceiling. That is decision 0007, and no
individual source shows it -- only putting the rows side by side does.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "calibration.md"

GENERATED = "<!-- generated by common/calibration.py; edit the sources, not this -->"

# Live Harbor runs: (task, row label, path to the reward.json, note).
LIVE = [
    ("mol-property-adapt", "oracle (shipped solution/)",
     "jobs/mol-oracle-modal/mol-property-adapt__Kkne97b/regrade/reward.json",
     "regrade through the refactored grader; the recorded original was 0.909661"),
    ("mol-property-adapt", "live agent (codex, k=1)",
     "jobs/mol-codex-modal/mol-property-adapt__NZofTg3/verifier/reward.json",
     "both eval sets clipped at recovery 1.0; raw 1.280 and 1.472"),
    ("qa-sft-adapt", "oracle (shipped solution/)",
     "jobs/qa-sft-oracle-modal/qa-sft-adapt__Spvo4Mn/verifier/reward.json", ""),
    ("qa-sft-adapt", "live agent (codex, k=1)",
     "jobs/qa-sft-codex-modal/qa-sft-adapt__heGKTWA/verifier/reward.json",
     "the only task that neither clipped to 1.0 nor floored to 0"),
    ("pref-reward-model", "oracle (shipped solution/)",
     "jobs/rm-oracle-modal/pref-reward-model__x5PH62H/verifier/reward.json",
     "1.3 sigma under a reference that is a five-seed mean"),
    ("pref-reward-model", "live agent (codex, k=1)",
     "jobs/rm-codex-modal/pref-reward-model__xicmHu5/regrade/reward.json",
     "scored 0.0 at the time by the false reject in decision 0009; 0.865 after the fix"),
    ("sciml-protein-regression", "oracle (shipped solution/)",
     "jobs/protein-oracle-gpu/sciml-protein-regression__egAHWfg/verifier/reward.json",
     "spearman 0.5733"),
    ("sciml-protein-regression", "frozen probe (no encoder adaptation)",
     "jobs/frozen-probe-check/frozen_head_only/regrade/reward.json",
     "spearman 0.5358 -- SCORES THE SAME AS THE ORACLE, see decision 0007"),
]

# Adversarial/broken fixtures, from committed records.
CRASH_MATRIX = ROOT / "research/results/crash_matrix.json"
FIXTURES = ROOT / "research/posttrain/results/verifier_fixtures.json"

# crash_matrix cases that are "does not adapt" rather than "broken".
CRASH_BENIGN = {"base", "constant"}

# Ordering failures that are acknowledged, tracked, and deliberately not fixed.
# Printed in full every run and rendered in the table; they do not fail the build,
# because a check that is permanently red stops being read. Anything not listed here
# is a NEW ordering failure and does fail. The goal is an empty dict -- this one
# empties when decision 0007 is acted on.
ACKNOWLEDGED = {
    "sciml-protein-regression":
        "decision 0007: the task scores three fixed tiers rather than normalized "
        "recovery, and both tiers sit below the on-contract frozen ceiling of "
        "0.5332, so a frozen probe ties the oracle at 1.0. The repair is unblocked "
        "-- scripts/lpft.json has base 0.5332, reference 0.5627 at 4.84 sigma -- and "
        "is deliberately deferred, not overlooked.",
}


def _cell(text: str) -> str:
    """Markdown table cells cannot contain a bare pipe."""
    return str(text).replace("|", "\\|")


def _reward(rel: str) -> float | None:
    p = ROOT / rel
    if not p.exists():
        return None
    return json.loads(p.read_text()).get("reward")


def collect() -> dict:
    """task -> {rows: [(label, reward, verdict, note)], sources: [...]}"""
    tasks: dict[str, dict] = {}

    def add(task: str, label: str, reward, verdict: str, note: str, source: str):
        t = tasks.setdefault(task, {"rows": [], "sources": []})
        t["rows"].append({"label": label, "reward": reward, "verdict": verdict,
                          "note": note})
        if source not in t["sources"]:
            t["sources"].append(source)

    # 1. Live Harbor runs.
    for task, label, rel, note in LIVE:
        r = _reward(rel)
        if r is None:
            continue
        add(task, label, r, "accepted", note, rel.split("/")[0] + "/")

    # 2. mol crash matrix.
    if CRASH_MATRIX.exists():
        src = str(CRASH_MATRIX.relative_to(ROOT))
        for case in json.loads(CRASH_MATRIX.read_text()):
            name, status = case["case"], case["status"]
            label = (f"no-adaptation input: {name}" if name in CRASH_BENIGN
                     else f"broken/hostile input: {name}")
            add("mol-property-adapt", label, case["reward"], status,
                f"expected {case['expected']}", src)

    # 3. Post-training fixtures.
    if FIXTURES.exists():
        doc = json.loads(FIXTURES.read_text())
        src = str(FIXTURES.relative_to(ROOT))
        measured = doc.get("_provenance", {}).get("measured")
        for task, cases in doc.get("tracks", {}).items():
            for name, c in sorted(cases.items()):
                if name == "oracle":
                    continue      # already covered by the live Harbor run
                kind = ("no-adaptation input" if name == "base_unchanged"
                        else "broken/hostile input")
                note = c.get("note", "")
                if not measured:
                    note = (note + "  (transcribed, not re-measured)").strip()
                add(task, f"{kind}: {name}", c.get("reward"),
                    "accepted" if c["verdict"] == "accept" else "rejected", note, src)

    return tasks


def ordering(task: str, rows: list[dict]) -> tuple[bool, str]:
    """The two properties §4 asks to be confirmed."""
    broken = [r for r in rows if r["label"].startswith("broken/hostile")]
    noadapt = [r for r in rows if r["label"].startswith("no-adaptation")
               or r["label"].startswith("frozen probe")]
    oracle = next((r for r in rows if r["label"].startswith("oracle")), None)

    bad = [r for r in broken if r["reward"] not in (0, 0.0)]
    if bad:
        return False, ("a broken or substituted input scored above zero: "
                       + ", ".join(f"{r['label']} = {r['reward']}" for r in bad))
    if oracle is None:
        return False, "no oracle run recorded, so there is nothing to order against"
    ties = [r for r in noadapt if r["reward"] is not None
            and r["reward"] >= oracle["reward"]]
    if ties:
        return False, ("a submission that does not adapt the model scores at or "
                       "above the oracle: "
                       + ", ".join(f"{r['label']} = {r['reward']}" for r in ties)
                       + f" vs oracle {oracle['reward']}")
    return True, (f"broken inputs all 0; every no-adaptation input below the "
                  f"oracle at {oracle['reward']}")


def render(tasks: dict) -> str:
    lines = [
        "# Verifier calibration",
        "",
        GENERATED,
        "",
        "What each verifier scored on inputs of known quality, and whether the",
        "ordering came out as expected. Required by the assignment's §4:",
        "",
        "> Run the verifier on at least: the untouched base model, the reference",
        "> counterpart, your probe fine-tune, a deliberately broken checkpoint, and",
        "> (if feasible) a deliberate reward-hacking attempt. **Report the reward each",
        "> produced and confirm the ordering matches expectation.** A verifier that has",
        "> only ever seen \"good\" inputs is untested.",
        "",
        "Assembled from the committed records rather than retyped, so it cannot drift",
        "from them. Regenerate with `python common/calibration.py`; `--check` fails if",
        "this file is stale **or if an ordering test fails**. Wired into CI.",
        "",
        "## Ordering",
        "",
        "| task | ordering as expected | |",
        "|---|---|---|",
    ]
    verdicts = {}
    for task in sorted(tasks):
        ok, why = ordering(task, tasks[task]["rows"])
        verdicts[task] = (ok, why)
        mark = "**yes**" if ok else ("**NO** (acknowledged)" if task in ACKNOWLEDGED
                                    else "**NO**")
        lines.append(f"| `{task}` | {mark} | {_cell(why)} |")

    lines += [
        "",
        "The protein failure is the reason this table is worth assembling: its frozen",
        "probe and its oracle both score 1.0, because both fixed tiers sit below the",
        "frozen ceiling of 0.5332. No individual source shows that -- only the rows",
        "side by side do. See [decision 0007](decisions/0007-protein-scores-three-fixed-tiers.md).",
        "",
    ]

    for task in sorted(tasks):
        t = tasks[task]
        lines += [f"## `{task}`", "",
                  "| input | reward | verdict | note |", "|---|---|---|---|"]
        for r in sorted(t["rows"], key=lambda r: (
                not r["label"].startswith("oracle"),
                not r["label"].startswith("live agent"),
                r["label"])):
            rw = "—" if r["reward"] is None else f"{r['reward']:g}"
            lines.append(f"| {_cell(r['label'])} | {rw} | {r['verdict']} | "
                         f"{_cell(r['note'])} |")
        lines += ["", "Sources: " + ", ".join(f"`{s}`" for s in t["sources"]), ""]

    wt = ROOT / "research/results/verifier_walltime.json"
    if wt.exists():
        doc = json.loads(wt.read_text())
        lines += [
            "## Verifier wall time",
            "",
            "A verifier that overruns its timeout scores an honest submission 0, so how",
            "close it runs to the limit is part of whether the reward is trustworthy.",
            "",
            "| task | measured | timeout | share of budget | eval sets |",
            "|---|---|---|---|---|",
        ]
        for task, m in sorted(doc["measurements"].items()):
            lines.append(f"| `{task}` | {m['seconds']}s | {m['timeout_s']}s | "
                         f"{m['fraction_of_budget']:.0%} | {m['eval_sets']} |")
        lines += ["", doc["conclusion"], "",
                  f"Source: `{wt.relative_to(ROOT)}`. "
                  + _cell(doc["_provenance"].get("note", "")), ""]

    lines += [
        "## What is not here",
        "",
        "- **The reference counterpart is not run as a submission on any task.** The",
        "  oracle stands in for it. On `mol-property-adapt` that substitution is known",
        "  to be unreliable: the oracle scores 0.6896 against a `reference_auc` of",
        "  0.7019, which is open question 1.",
        "- **`sciml-protein-regression` has no broken-input row here.** Its hardening",
        "  suite (`scripts/modal_verify_hardening.py`) runs on Modal and its committed",
        "  record covers the mol grader, not this one.",
        "- The two post-training tracks' fixture rows are transcribed from the recorded",
        "  run until `verify_graders.py` is next executed, which now writes them as data.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    tasks = collect()
    if not tasks:
        print("no calibration records found -- this report checked nothing")
        return 1
    want = render(tasks)
    failed = [t for t in sorted(tasks) if not ordering(t, tasks[t]["rows"])[0]]

    if args.check:
        problems = []
        if not OUT.exists() or OUT.read_text() != want:
            problems.append("docs/calibration.md is stale; run "
                            "`python common/calibration.py`")
        for t in failed:
            why = ordering(t, tasks[t]["rows"])[1]
            if t in ACKNOWLEDGED:
                print(f"  known, tracked, not fixed -- {t}: {why}")
                print(f"    why not fixed: {ACKNOWLEDGED[t]}")
            else:
                problems.append(f"{t}: NEW ordering failure -- {why}")
        if problems:
            for p in problems:
                print(f"  {p}")
            return 1
        print(f"calibration ok: {len(tasks)} tasks, "
              f"{sum(len(v['rows']) for v in tasks.values())} recorded inputs, "
              "every ordering as expected")
        return 0

    OUT.write_text(want)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(tasks)} tasks, "
          f"{sum(len(v['rows']) for v in tasks.values())} inputs)")
    for t in failed:
        print(f"  ORDERING FAILS -- {t}: {ordering(t, tasks[t]['rows'])[1]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
