"""The reward's decision log: validate it, and regenerate its index.

Why this exists
---------------
The reward's *current state* is now machine-readable -- anchors carry the rule version
that screened them and the commit that wrote them. Its *history* was not. It lived as
prose in eleven files: thirty-two passages narrating a change ("the earlier bar was",
"previously written up as", "no longer"), with no index and no way to ask which
decision superseded which.

`docs/decisions/` holds one record per decision, in the MADR shape, with Nygard's
supersession convention: a reversed decision is kept and marked, because "it's still
relevant to know that it *was* the decision, but is *no longer* the decision".

This script is what stops the log rotting the way the prose did:

    python common/decisions.py            # rewrite docs/decisions/README.md
    python common/decisions.py --check    # exit 1 if the index is stale or a link breaks

What it validates
-----------------
  * `id` matches the filename, and ids are unique and contiguous from 1
  * `status` is one of the allowed values
  * every `supersedes` / `superseded_by` target exists
  * the two are symmetric -- if A supersedes B then B is superseded_by A. A one-sided
    link is how a supersession chain silently loses its history
  * a record marked `superseded` names what replaced it, and one that is not, does not
  * `affects` names real task directories
  * the committed index matches what this script would generate

Frontmatter is parsed with a deliberately small reader rather than PyYAML: this runs
in CI beside `sync.py` and `check_reward.py`, and none of those may need a dependency.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DECISIONS = ROOT / "docs" / "decisions"
INDEX = DECISIONS / "README.md"

STATUSES = {"accepted", "accepted (repairable)", "superseded", "proposed", "rejected"}

GENERATED_MARKER = "<!-- generated by common/decisions.py; edit the records, not this -->"


def _parse_scalar(raw: str) -> object:
    raw = raw.strip()
    if raw in ("null", "~", ""):
        return None
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        if not inner:
            return []
        return [_parse_scalar(x) for x in inner.split(",")]
    if re.fullmatch(r"-?\d+", raw):
        return int(raw)
    return raw.strip("'\"")


def load_records() -> list[dict]:
    """Every record's frontmatter, plus its path and title, ordered by id."""
    records = []
    for path in sorted(DECISIONS.glob("[0-9][0-9][0-9][0-9]-*.md")):
        text = path.read_text()
        m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
        if not m:
            raise SystemExit(f"{path.name}: no frontmatter block")
        meta: dict = {"path": path}
        for line in m.group(1).splitlines():
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            if ":" not in line:
                raise SystemExit(f"{path.name}: cannot parse frontmatter line {line!r}")
            key, _, val = line.partition(":")
            meta[key.strip()] = _parse_scalar(val)
        records.append(meta)
    return sorted(records, key=lambda r: r["id"])


def validate(records: list[dict]) -> list[str]:
    fails: list[str] = []
    by_id = {r["id"]: r for r in records}
    tasks = {d.name for d in (ROOT / "tasks").iterdir() if d.is_dir()}

    for i, r in enumerate(records, start=1):
        name = r["path"].name
        if r["id"] != i:
            fails.append(f"{name}: id {r['id']} is not contiguous (expected {i})")
        if not name.startswith(f"{r['id']:04d}-"):
            fails.append(f"{name}: filename does not start with its id {r['id']:04d}")
        if r.get("status") not in STATUSES:
            fails.append(f"{name}: status {r.get('status')!r} not in {sorted(STATUSES)}")
        for t in r.get("affects") or []:
            if t not in tasks:
                fails.append(f"{name}: affects unknown task {t!r}")

        sb = r.get("superseded_by")
        if r.get("status") == "superseded" and sb is None:
            fails.append(f"{name}: status is superseded but superseded_by is null, so "
                         "what replaced it is unrecorded")
        if sb is not None and r.get("status") != "superseded":
            fails.append(f"{name}: superseded_by is set but status is "
                         f"{r.get('status')!r}")
        if sb is not None and sb not in by_id:
            fails.append(f"{name}: superseded_by {sb} does not exist")
        elif sb is not None and r["id"] not in (by_id[sb].get("supersedes") or []):
            fails.append(f"{name}: says superseded_by {sb}, but {sb:04d} does not list "
                         f"{r['id']} in supersedes -- a one-sided link loses the chain")

        for target in r.get("supersedes") or []:
            if target not in by_id:
                fails.append(f"{name}: supersedes {target} which does not exist")
            elif by_id[target].get("superseded_by") != r["id"]:
                fails.append(f"{name}: supersedes {target}, but {target:04d} does not "
                             f"point back at {r['id']}")
    return fails


def render_index(records: list[dict]) -> str:
    lines = [
        "# Reward design decisions",
        "",
        GENERATED_MARKER,
        "",
        "One record per decision about how the reward is computed, in the order they",
        "were made. A reversed decision is kept and marked `superseded` rather than",
        "deleted: it is still relevant to know that it *was* the decision.",
        "",
        "Regenerate with `python common/decisions.py`; `--check` fails if this file is",
        "stale or a supersession link is one-sided. Wired into CI.",
        "",
        "| # | decision | status | date | links |",
        "|---|---|---|---|---|",
    ]
    for r in records:
        links = []
        for t in r.get("supersedes") or []:
            links.append(f"supersedes [{t:04d}](#)".replace("(#)", f"({_fname(records, t)})"))
        if r.get("superseded_by") is not None:
            sb = r["superseded_by"]
            links.append(f"**superseded by [{sb:04d}]({_fname(records, sb)})**")
        status = r["status"]
        if status == "superseded":
            status = f"~~{status}~~"
        lines.append(f"| {r['id']:04d} | [{r['title']}]({r['path'].name}) | {status} "
                     f"| {r['date']} | {', '.join(links) or '—'} |")

    # The deviation view: which decisions moved a number that had already shipped.
    # Distinct from the table above, which is chronological -- this is the "what
    # changed, and does it affect a published figure" question a reader arrives with.
    lines += [
        "",
        "## Which of these moved a number that had already shipped",
        "",
        "| decision | what moved | reader impact |",
        "|---|---|---|",
        "| [0003](0003-anchors-measured-on-contract-only.md) | mol anchors: base 0.643 → 0.6341, reference 0.7324 → 0.7019 | every mol reward before it was normalized between two unreachable points |",
        "| [0004](0004-bbbp-split-rebuilt.md) | bbbp held-out set 204 → 407 rows | anchors re-measured; the random-init control was not, so Gate A is unmeasured there |",
        "| [0006](0006-shipping-bar-derived-from-tolerance.md) | bar 3.0σ → 4.0σ; `band >= 0.02` removed | `pref-reward-model` passed before and does not now; it ships stamped provisional |",
        "| [0009](0009-lineage-floor-applies-to-weight-matrices-only.md) | 1-D tensors no longer reject | one agent trial went 0.0 → 0.865 |",
        "| [0010](0010-band-sigma-divides-by-the-larger-arm.md) | tox21 6.48σ → 7.62σ, bbbp 4.09σ → 6.81σ, meltome 3.92σ → 4.84σ | no reward changed; six files of prose did. bbbp's \"tightest band that ships at 4.09σ\" was never real |",
        "| [0011](0011-contamination-tripwire-is-derived.md) | mol `t_implausible` 0.85 → 0.86, 0.97 → 0.98 | tripwire loosens; no recorded trial changes verdict |",
        "| [0012](0012-integrity-gate-is-per-submission.md) | mol gate per-eval-set → global | a half-substituted submission scored 0.5 and now scores 0.0 |",
        "",
        "Everything else added a check, a measurement or a record without moving a",
        "published figure.",
    ]
    return "\n".join(lines) + "\n"


def _fname(records: list[dict], rid: int) -> str:
    for r in records:
        if r["id"] == rid:
            return r["path"].name
    return "#"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    records = load_records()
    fails = validate(records)
    want = render_index(records)

    if args.check:
        if not INDEX.exists():
            fails.append("docs/decisions/README.md is missing; run "
                         "`python common/decisions.py`")
        elif INDEX.read_text() != want:
            fails.append("docs/decisions/README.md is stale; run "
                         "`python common/decisions.py`")
        if fails:
            for f in fails:
                print(f"  {f}")
            print(f"\n{len(fails)} problem(s) in the decision log")
            return 1
        print(f"decision log ok: {len(records)} records, index current, "
              "every supersession link two-sided")
        return 0

    if fails:
        for f in fails:
            print(f"  {f}")
        print(f"\nrefusing to write the index: {len(fails)} problem(s) above")
        return 1
    INDEX.write_text(want)
    print(f"wrote {INDEX.relative_to(ROOT)} ({len(records)} records)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
